// <auto-generated />
using API_TASK;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_TASK.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230824155715_royal")]
    partial class royal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API_TASK.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "T-Shirt",
                            Country = "Azerbaijan",
                            Description = "Beatiful",
                            Number = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Cup",
                            Country = "Turkiye",
                            Description = "Perfect",
                            Number = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Uniform",
                            Country = "Pakistan",
                            Description = "Nice",
                            Number = 3
                        });
                });

            modelBuilder.Entity("API_TASK.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("PersonAge")
                        .HasColumnType("int");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PersonNumber")
                        .HasColumnType("int");

                    b.Property<string>("PersonSurname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PersonAge = 22,
                            PersonName = "Royal",
                            PersonNumber = 1,
                            PersonSurname = "Humbetov"
                        },
                        new
                        {
                            Id = 2,
                            PersonAge = 19,
                            PersonName = "Xeyal",
                            PersonNumber = 2,
                            PersonSurname = "Humbetli"
                        },
                        new
                        {
                            Id = 3,
                            PersonAge = 12,
                            PersonName = "Xeyyam",
                            PersonNumber = 3,
                            PersonSurname = "Humbetli"
                        });
                });

            modelBuilder.Entity("API_TASK.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = 1,
                            ProductDescription = "Description",
                            ProductName = "Testr"
                        },
                        new
                        {
                            Id = 2,
                            Number = 2,
                            ProductDescription = "Descript",
                            ProductName = "assdf"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
